#!/usr/bin/env python3
from enum import Enum
import sys
from glob import glob


class Token(Enum): #Key/Token enum
    tid = 258
    number = 259
    assign = 260
    predef = 261
    tempty = 262
    undef = 263
    error = 264
    typ = 265
    eof = ord("$")
    lpar = ord("(")
    rpar = ord(")")
    mul = ord("*")
    add = ord("+")
    comma = ord(",")
    sub = ord("-")
    dot = ord(".")
    div = ord("/")
    colon = ord(":")
    semcol = ord(";")
    equal = ord("=")

    program = 268
    tinput = 269
    output = 270
    var = 271
    begin = 272
    end = 273
    boolean = 274
    integer = 275
    real = 276

class Optab:
    optab = [
        [Token.add, Token.integer, Token.integer, Token.integer],
        [Token.add, Token.real,    Token.real,    Token.real],
        [Token.add, Token.integer, Token.real,    Token.real],
        [Token.add, Token.real,    Token.integer, Token.real],
        [Token.mul, Token.integer, Token.integer, Token.integer],
        [Token.mul, Token.real,    Token.real,    Token.real],
        [Token.mul, Token.integer, Token.real,    Token.real],
        [Token.mul, Token.real,    Token.integer, Token.real]
    ] 

    @staticmethod
    def getOType(op, left, right):
        for row in Optab.optab:
            if op == row[0] and left == row[1] and right == row[2]:
                return row[3]
        return Token.undef



class KeyTokTab:
    tokentab = {
        "id":     Token.tid,
        "number": Token.number,
        ":=": 	  Token.assign,
        "undef":  Token.undef,
        "predef": Token.predef,
        "tempty": Token.tempty,
        "error":  Token.error,
        "type":   Token.typ,
        "$":      Token.eof,
        "(":      Token.lpar,
        ")":      Token.rpar,
        "*":      Token.mul,
        "+":      Token.add,
        ",":      Token.comma,
        "-":      Token.sub,
        ".":      Token.dot,
        "/":      Token.div,
        ":":      Token.colon,
        ";":      Token.semcol,
        "=":      Token.equal
    }

    keywordtab = {
        "program": Token.program,
        "input":   Token.tinput,
        "output":  Token.output,
        "var": 	   Token.var,
        "begin":   Token.begin,
        "end": 	   Token.end,
        "boolean": Token.boolean,
        "integer": Token.integer,
        "real":    Token.real,
    }
    
    @staticmethod
    def lex2tok(lexeme):
        if lexeme in KeyTokTab.tokentab.keys(): #Might have to be tokentab.keys()
            return KeyTokTab.tokentab[lexeme]
        return KeyTokTab.key2tok(lexeme)

    @staticmethod
    def key2tok(lexeme):
        if lexeme in KeyTokTab.keywordtab.keys(): #Might have to be keywordtab.keys()
            return KeyTokTab.keywordtab[lexeme]
        return Token.tid

    @staticmethod
    def tok2lex(token):
        keys = [key for key, value in KeyTokTab.tokentab.items() if value == token]
        if len(keys) == 1:
            return keys[0]
        keys = [key for key, value in KeyTokTab.keywordtab.items() if value == token]
        if len(keys) == 1:
            return keys[0]

class Symbol:
    def __init__(self, name, role, type, size, addr):
        self.name = name
        self.role = role
        self.type = type
        self.size = size
        self.addr = addr


class Symtab:
    NOTFOUND = -1
    def __init__(self):
        self.table = list()
        self.addRow(KeyTokTab.tok2lex(Token.predef), Token.typ, Token.predef, 0, 0)
        self.addRow(KeyTokTab.tok2lex(Token.undef), Token.typ, Token.predef, 0, 0)
        self.addRow(KeyTokTab.tok2lex(Token.error), Token.typ, Token.predef, 0, 0)
        self.addRow(KeyTokTab.tok2lex(Token.integer), Token.typ, Token.predef, 4, 0)
        self.addRow(KeyTokTab.tok2lex(Token.boolean), Token.typ, Token.predef, 4, 0)
        self.addRow(KeyTokTab.tok2lex(Token.real), Token.typ, Token.predef, 8, 0)
        self.startP = len(self.table)
    
    def addRow(self, name, role, type, size, addr):
        self.table.append(Symbol(name, role, type, size, addr))

    def getName(self, index):
        return self.table[index].name        
    def getRole(self, index):
        return self.table[index].role        
    def getType(self, index):
        return self.table[index].type    
    def getSize(self, index):
        return self.table[index].size    
    def getAddr(self, index):
        return self.table[index].addr
    def setSize(self, index, size):
        self.table[index].size = size



    def pSymtab(self):
        print("________________________________________________________ ")
        print("________________________________________________________ \n THE SYMBOL TABLE\n________________________________________________________ ")
        print("       NAME       ROLE       TYPE      SIZE      ADDR     \n________________________________________________________ ")
        for i in range(self.startP, len(self.table)):
            print("{:>11s} {:>10s} {:>10s} {:9d} {:9d} ".format(self.getName(i), KeyTokTab.tok2lex(self.getRole(i)), KeyTokTab.tok2lex(self.getType(i)), self.getSize(i), self.getAddr(i)))
        print("________________________________________________________ \n STATIC STORAGE REQUIRED is", self.getSize(self.startP) if self.startP != len(self.table) else 0, "BYTES\n________________________________________________________ ")
        
    def addProgName(self, name):
        self.startP = len(self.table)
        self.addRow(name, Token.program, Token.program, 0, 0)
    
    def addVarName(self, name):
        self.addRow(name, Token.var, Token.undef, 0, 0)
    
    def findName(self, name):
        for symbol in self.table:
            if name == symbol.name:
                return True
        return False

    def setVarTyp(self, type):
        for i, symbol in enumerate(self.table):
            if symbol.role == Token.var and symbol.type == Token.undef:
                symbol.type = type
                if type not in [Token.integer, Token.boolean, Token.real]:
                    symbol.type = Token.error
                symbol.size = self.getSize(self.getRef(KeyTokTab.tok2lex(type)))
                symbol.addr = self.getSize(i-1) + self.getAddr(i-1)
        self.setSize(self.startP, self.getSize(-1) + self.getAddr(-1)) # -1 on the index will grab the last item in the list
    
    def getNameType(self, name):
        return self.getType(self.getRef(name)) if self.getRef(name) != -1 else Token.undef

    def getRef(self, name):
        for i, symbol in enumerate(self.table):
            if symbol.name == name:
                return i
        return Symtab.NOTFOUND


class Reader: 
    def __init__(self, filename):
        try:
            with open(filename) as infile:
                self.buffer = infile.read() + "$"
        except OSError:
            print("Error:", filename, "Not Found")
            sys.exit()

    def getProg(self):
        return self.buffer


class Lexer: 
    def __init__(self, reader):
        self.pbuffer = reader.getProg()
        print("\n________________________________________________________ \n THE PROGRAM TEXT\n________________________________________________________ ");
        print(self.pbuffer,)
        print("________________________________________________________ ")
        self.lbuffer = ""
        self.pbuffpointer = 0
    #Public methods
    def getToken(self):
        self._skipWhitespace()
        self._readLex()
        if self.lbuffer.isnumeric():
            return KeyTokTab.lex2tok("number")
        if KeyTokTab.lex2tok(self.lbuffer) in [Token.number, Token.undef, Token.predef, Token.tempty, Token.error, Token.typ]:
            return KeyTokTab.key2tok(self.lbuffer)
        return KeyTokTab.lex2tok(self.lbuffer)
    
    def getLex(self):
        return self.lbuffer
    #Private methods
    def _incPbuff(self):
        temp = self.pbuffpointer + 0
        self.pbuffpointer += 1
        return temp

    def _getChar(self):
        self.lbuffer += self.pbuffer[self._incPbuff()]

    def _skipWhitespace(self):
        while self.pbuffer[self.pbuffpointer].isspace():
            self._incPbuff()
    
    def _readLex(self):
        self.lbuffer = ""
        while not self.pbuffer[self.pbuffpointer].isspace() and self.pbuffer[self.pbuffpointer] not in [ "(", ")", ",", ".", ":", ";"] and self.pbuffpointer < len(self.pbuffer) - 1:
            self._getChar()
            if self.lbuffer.isnumeric() and not self.pbuffer[self.pbuffpointer].isnumeric():
                break
        if len(self.lbuffer) < 1:
            self._getChar()
            if self.lbuffer == ":" and self.pbuffer[self.pbuffpointer] == "=":
                self._getChar()
        

class Parser:
    #Public methods
    def parse(self, filename):
        self.isparseok = True
        self.lexer = Lexer(Reader(filename))
        self.lookahead = self.lexer.getToken()
        self.symtab = Symtab()
        if self.lookahead == Token.eof:
            print("SYNTAX:   Input file is empty ")
            self.isparseok = False
        else:
            self._programHeader()
            self._varPart()
            self._statPart()
            self._eof()
            if self.isparseok:
                print("PARSE SUCCESSFUL! ")
        self.symtab.pSymtab()
        return self.isparseok
    #Private methods
    def _eof(self):
        if self.lookahead != Token.eof:
            self.isparseok = False
            print("SYNTAX:   Extra symbols after end of parse! \n          ", end="")
            while self.lookahead != Token.eof:
                print(self.lexer.getLex(), end=" ")
                self.lookahead = self.lexer.getToken()
            print()
    def _match(self, token):
        if self.lookahead == token: self.lookahead = self.lexer.getToken()
        else:
            self.isparseok = 0
            if token == Token.typ:
                print("SYNTAX:   Type name expected found {} ".format(self.lexer.getLex()))
            elif token == Token.tid:
                print("SYNTAX:   ID expected found {} ".format(self.lexer.getLex()))
            else:
                print("SYNTAX:   Symbol expected", KeyTokTab.tok2lex(token), "found {} ".format(self.lexer.getLex()))

    def _programHeader(self):
        self._match(Token.program)
        if self.lookahead != Token.tid: self.symtab.addProgName("???")
        else: self.symtab.addProgName(self.lexer.getLex())
        for token in [Token.tid, Token.lpar, Token.tinput, Token.comma, Token.output, Token.rpar, Token.semcol]:
            self._match(token)
    
    def _varPart(self):
        self._match(Token.var)
        self._varDecList()
    
    def _varDecList(self):
        self._varDec()
        if self.lookahead == Token.tid: self._varDecList()

    def _varDec(self):
        self._idList()
        self._match(Token.colon)
        self.symtab.setVarTyp(self.lookahead)
        if self.lookahead in [Token.integer, Token.boolean, Token.real]: self._match(self.lookahead)
        else: self._match(Token.typ)
        self._match(Token.semcol)
    
    def _idList(self):
        if not self.symtab.findName(self.lexer.getLex()) and self.lookahead == Token.tid: self.symtab.addVarName(self.lexer.getLex())
        else: 
            if self.lookahead == Token.tid: print("SEMANTIC: ID already declared:", self.lexer.getLex())
            self.isparseok = False

        self._match(Token.tid)
        if self.lookahead == Token.comma:
            self._match(Token.comma)
            self._idList()
    
    def _statPart(self):
        self._match(Token.begin)
        self._statList()
        self._match(Token.end)
        self._match(Token.dot)
    
    def _statList(self):
        self._stat()
        if self.lookahead == Token.semcol:
            self._match(Token.semcol)
            self._statList()
    
    def _stat(self):
        leftside = self.symtab.getNameType(self.lexer.getLex())
        if not self.symtab.findName(self.lexer.getLex()) and self.lookahead == Token.tid:
            print("SEMANTIC: ID NOT declared:", self.lexer.getLex())
            leftside = Token.error
        if self.lookahead != Token.tid: leftside = Token.error
        self._match(Token.tid)
        self._match(Token.assign)
        rightside = self._expr()
        if leftside != rightside:
            print("SEMANTIC: Assign types: {} := {}".format(KeyTokTab.tok2lex(leftside), KeyTokTab.tok2lex(rightside)))
            self.isparseok = False

    def _expr(self):
        leftside = self._term()
        if self.lookahead == Token.add:
            self._match(Token.add)
            return Optab.getOType(Token.add, leftside, self._expr())
        return leftside

    def _term(self):
        leftside = self._factor()
        if self.lookahead == Token.mul:
            self._match(Token.mul)
            return Optab.getOType(Token.mul, leftside, self._factor())
        return leftside

    def _factor(self):
        if self.lookahead == Token.lpar:
            self._match(Token.lpar)
            temp = self._expr()
            self._match(Token.rpar)
            return temp
        return self._operand()
    
    def _operand(self):
        if self.lookahead == Token.tid:
            temp = self.symtab.getNameType(self.lexer.getLex())
            if not self.symtab.findName(self.lexer.getLex()):
                print("SEMANTIC: ID NOT declared:", self.lexer.getLex())
                self.isparseok = False
                temp = Token.undef
            self._match(Token.tid)
            return temp
        if self.lookahead == Token.number:
            self._match(Token.number)
            return Token.integer
        print("SYNTAX:   Operand Expected ")
        self.isparseok = False
        return Token.error

def main():
    parser = Parser()
    temp = glob("TestSuite/*.pas")
    temp.sort()
    for filename in temp:
        print("testing", filename)
        parser.parse(filename)    

if __name__ == "__main__":
    main()